Milestone 1- Project Setup
george-shammar/math-calc-app pull request #1
Opened 2021-07-05 21:55 UTC by george-shammar

This Pull Request seeks to merge the changes arising from the project set up to the default branch.

2021-07-05 22:20 UTC, taiwo2 requested changes
# STATUS: INVALID 🔴 
@george-shammar well-done, Your project was invalidated due to a lack of descriptive PR. make it descriptive to tell what the milestone project meant to do.

2021-07-05 22:49 UTC, bellom requested changes
## Hi @george-shammar  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**1. Kindly update your `README` file**
**Let's make your repo look more professional by updating your `README` file**.
Checkout out the below link for help, feel free to follow this [Microverse template](https://github.com/microverseinc/readme-template) from pathwright

**2. Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best**

2021-07-05 22:49 UTC, bellom commented on src/App.css
>    }
I think you should delete this file and any other unnecessary files, as well as the React svg Logo.
![image](https://user-images.githubusercontent.com/31897434/124522487-55b65d80-ddeb-11eb-9db0-718d6f1f9bf6.png)

2021-07-06 14:31 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- Readme updated :+1: 

To improve :factory_worker: [REQUIRED]:

- [ ] Please fix the MIT link, and use tools like Grammarly to help you with your readme as it is the first thing users check.
- [ ] It will be nice if you remove all unnecessary files like: App.test.js, reportWebVitals.js, and setupTests.js. 
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone1/files-removed.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896085/))

Nice to have [OPTIONAL] :

- [ ] As you are using ES6 syntax, please use the arrow function instead of the function keyword.
- [ ] It will be nice if you update the live demo based on the modifications that you made.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-07-06 14:31 UTC, rindrajosia commented on README.md
> +This is a simple calculator application developed to demonstrate React.js's functionality and for educational purpose.
This is a simple calculator application developed to demonstrate React.js's functionality and for educational `purposes.`

2021-07-06 15:07 UTC, george-shammar commented on README.md
> +This is a simple calculator application developed to demonstrate React.js's functionality and for educational purpose.
@rindrajosia, This comment is not clear. I'm not sure what is required.

2021-07-06 15:40 UTC, rindrajosia commented on README.md
> +This is a simple calculator application developed to demonstrate React.js's functionality and for educational purpose.
Instead of Purpose, it should be Purposes

2021-07-06 15:45 UTC, george-shammar commented on README.md
> +This is a simple calculator application developed to demonstrate React.js's functionality and for educational purpose.
Okay. :smiley:

2021-07-06 16:26 UTC, enaburekhan approved these changes
# Status: Approve:heavy_check_mark:
**Hi George!
Congratulations:clap::clap:. Thank you for implementing the changes requested by the last reviewer.
Move on with the next milestone:walking:.**

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

2021-07-06 16:36 UTC, merged