Milestone 2- Basic Components
george-shammar/math-calc-app pull request #2
Opened 2021-07-06 22:26 UTC by george-shammar

This Pull Request seeks to merge the following features to the default branch:

1. App Component
2. Button Component
3. ButtonPanel Component
4. Display Component

These Components have been implemented with basic features as per the requirements of Milestone-2

2021-07-06 23:14 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @george-shammar, congratulations on this milestone :fireworks: The PR and README is professional :smile: Commit messages easy to understand :smile: The App, Button, ButtonPanel, and the Display components implemented as expected :+1: The right linter config files were used :1st_place_medal: Awesome
However, there is an inline ESLint disabling rule in the ButtonPanel component which needs to be removed. Kindly check the comment below

Once this is resolved, kindly submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-07-06 23:14 UTC, addod19 commented on src/components/ButtonPanel.js
> +/* eslint-disable */
Kindly avoid inline disabling rules, it is almost the same as altering the config files

2021-07-06 23:14 UTC, addod19 commented on src/components/ButtonPanel.js
> +  /* eslint-enable */
Kindly avoid inline disabling rules, it is almost the same as altering the config files

2021-07-07 16:33 UTC, rukundoeric approved these changes
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - Follows gitwork-flow.  💯
  - Codebase looks clean and professional. 💯 
  

- ### To Improve
  - N/A

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/),
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

2021-07-07 16:36 UTC, merged