Milestone 4- Calculations and Operations
george-shammar/math-calc-app pull request #3
Opened 2021-07-08 21:12 UTC by george-shammar

This Pull Request seeks to merge the following features to the development branch:

1. Creation of calculate function in Calculate.js
2. Creation of operate function to handle operations.
3. Assigning button names to operations.
4. Implementing big.js to handle big numbers.

2021-07-08 22:58 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @george-shammar, great job on the project :fireworks: Right linter files used, calculate.js file imported in the App component :smile: calculate.js module implemented well :+1: However, our operate.js file needs a little work, kindly check the comment below:

- The operate.js switches operation and uses plus, minus, times, div, and modifier for manipulating data

Once these are resolved, kindly submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

2021-07-08 22:58 UTC, addod19 commented on src/logic/Operate.js
> +    result = new Big(numberOne + numberTwo);
Kindly use `plus` instead of the `+` used currently, for instance `numberOne.plus(numberTwo)`

2021-07-08 22:58 UTC, addod19 commented on src/logic/Operate.js
> +    result = new Big(numberOne - numberTwo);
Kindly use minus instead of the `-` used currently, for instance `numberOne.minus(numberTwo)`

2021-07-08 22:58 UTC, addod19 commented on src/logic/Operate.js
> +    result = new Big(numberOne / numberTwo);
Kindly use `div` instead of the `/` used currently, for instance `numberOne.div(numberTwo)`

2021-07-09 06:07 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work making the requested changes.
### Highlights 🌵 🌵 🌵 
- `+`, `-` and `/` operations updated

### Change(s) 🔕 🔕 🔕 
- Check comments


### Martin Afani
#### Slack: whiz25

2021-07-09 06:07 UTC, afanimartin commented on src/logic/Operate.js
>      result = new Big(numberOne * numberTwo);
- Use: `result = new Big(numberOne.times(numberTwo))`

2021-07-09 13:33 UTC, Elbie-em requested changes
## STATUS: CHANGES REQUIRED 🟡  ♻️ 

Hi, @george-shammar, you have made some great progress so far, however, there are just a few changes you need to apply so that this milestone can be approved and you can move forward. Kindly check my comments below ⬇️ 

*All the best, you are almost there* 💪 

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-07-09 13:33 UTC, Elbie-em commented on src/logic/Operate.js
> +  if (operation === '+') {
- [ ] both numberOne and numberTwo should be wrapped in big.js, here is how you could handle it.
```
const num1 = Big(numberOne)
const num2 = Big(numberTwo)
```
There is no need to create a new instance of the Big in each condition, e.g your '+' operation will simply become

`result = num1.plus(num2);`

2021-07-09 13:33 UTC, Elbie-em commented on src/logic/Operate.js
>      result = new Big(numberOne * numberTwo);
- [ ] Kindly apply the change requested by the previous TSE above regarding 'times', with the wrapping is will simply be
`resullt = num1.times(num2);`

2021-07-09 13:33 UTC, Elbie-em commented on src/logic/Operate.js
> +    result = new Big(numberOne.div(numberTwo));
#### [OPTIONAL]

- [ ] Division by 0 will throw an error, I recommend you wrap this case in a try-catch block.

2021-07-10 07:19 UTC, uche-inyama approved these changes
## Approved :heavy_check_mark: 

### Hi George :slightly_smiling_face: 

The mandatory changes from the last review were implemented. Go on with the next milestone.

### Happy coding :wave: 

#### ``` Uchechukwu Henry Inyama ```

2021-07-10 11:54 UTC, merged